// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsUxpWXL_Y8Y57DyeC6iq-yOecYc67adc',
    appId: '1:426066420376:web:6431b1ac31a8ea5358a6ed',
    messagingSenderId: '426066420376',
    projectId: 'fir-auth-4d081',
    authDomain: 'fir-auth-4d081.firebaseapp.com',
    storageBucket: 'fir-auth-4d081.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGq-GRiSYFCXViONds0Y4HoTuwERYdvU',
    appId: '1:426066420376:android:97a5addd69d9a18858a6ed',
    messagingSenderId: '426066420376',
    projectId: 'fir-auth-4d081',
    storageBucket: 'fir-auth-4d081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_wz42GsM0Asv110zZPH2ngbkNklaIJ_A',
    appId: '1:426066420376:ios:4ca28e05b952a8cb58a6ed',
    messagingSenderId: '426066420376',
    projectId: 'fir-auth-4d081',
    storageBucket: 'fir-auth-4d081.firebasestorage.app',
    iosBundleId: 'com.example.kanjiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_wz42GsM0Asv110zZPH2ngbkNklaIJ_A',
    appId: '1:426066420376:ios:4ca28e05b952a8cb58a6ed',
    messagingSenderId: '426066420376',
    projectId: 'fir-auth-4d081',
    storageBucket: 'fir-auth-4d081.firebasestorage.app',
    iosBundleId: 'com.example.kanjiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsUxpWXL_Y8Y57DyeC6iq-yOecYc67adc',
    appId: '1:426066420376:web:238b96360fa657e758a6ed',
    messagingSenderId: '426066420376',
    projectId: 'fir-auth-4d081',
    authDomain: 'fir-auth-4d081.firebaseapp.com',
    storageBucket: 'fir-auth-4d081.firebasestorage.app',
  );
}
